### ISSUE TITLE
Rating view is throwing error on gradle build

### ISSUE THREAD

**Issue by lokeshsuhas** [xiprox/SimpleRatingView#1]
Error:A problem occurred configuring project ':app'.

> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not resolve com.github.xiprox.simpleratingview:library:+.
>      Required by:
>          FoodieClient:app:unspecified
>       > Failed to list versions for com.github.xiprox.simpleratingview:library.
>          > Unable to load Maven meta-data from https://jcenter.bintray.com/com/github/xiprox/simpleratingview/library/maven-metadata.xml.
>             > Could not GET 'https://jcenter.bintray.com/com/github/xiprox/simpleratingview/library/maven-metadata.xml'.
>                > peer not authenticated
>       > Failed to list versions for com.github.xiprox.simpleratingview:library.
>          > Unable to load Maven meta-data from https://jitpack.io/com/github/xiprox/simpleratingview/library/maven-metadata.xml.
>             > Could not GET 'https://jitpack.io/com/github/xiprox/simpleratingview/library/maven-metadata.xml'.
>                > peer not authenticated

**Comment by xiprox** [comment]
Hmm. Looks like something is wrong on your end. Mind posting your gradle files?

**Comment by xiprox** [comment]
Hello, were you able to solve this?

**Comment by lokeshsuhas** [comment]
i have just directly included the code inside the project. it solved the
issue.

**Comment by xiprox** [comment]
I see. Good luck with your project then.
