### ISSUE TITLE
setIconColor is not working

### ISSUE THREAD

**Issue by chaimleu** [xiprox/SimpleRatingView#2]
I am trying to change the icon color to blue if the status is neutral but it stuck at the default color,
What have I done wrong?
This is my code:

ratingBookStars.setOnRatingChangedListener(new SimpleRatingView.OnRatingChangeListener() {
                @Override
                public void onRatingChanged(SimpleRatingView.Rating ratingType) {
                    switch (ratingType) {
                        case POSITIVE:
                            stars = 3;
                            break;
                        case NEUTRAL:
                            stars = 2;
                            ratingBookStars.setIconColor(Color.BLUE);
                            break;
                        case NEGATIVE:
                            stars = 1;
                            break;
                    }
                }
            });

Thanks,
Haim.

**Comment by xiprox** [comment]
It was a silly mistake on my part. I've pushed version `1.1.0` to maven. You should be able to use it in an hour or so. Good luck with your project!
